# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch


# Create random tensor
rand_tensor = torch.rand(size=(7,7))

rand_tensor


tensor([[0.7986, 0.5575, 0.3722, 0.8791, 0.8489, 0.0102, 0.2419],
        [0.1116, 0.8828, 0.9879, 0.6410, 0.6140, 0.3646, 0.3637],
        [0.1324, 0.0551, 0.4866, 0.8938, 0.1179, 0.7257, 0.9650],
        [0.1586, 0.6065, 0.7759, 0.9012, 0.4656, 0.0519, 0.3288],
        [0.2645, 0.9352, 0.2007, 0.3317, 0.4341, 0.8156, 0.4012],
        [0.7315, 0.7929, 0.3638, 0.0894, 0.4400, 0.8928, 0.8245],
        [0.8763, 0.0349, 0.7148, 0.3257, 0.1226, 0.1773, 0.2713]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
rand_tensor_2 = torch.rand(size=(1,7))

# Perform matrix multiplication 
rand_tensor @ rand_tensor_2.T


tensor([[1.6189],
        [1.5243],
        [1.4682],
        [1.1595],
        [1.6835],
        [2.2373],
        [1.4424]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
rand_tensor_again = torch.rand(size=(7,7))
rand_tensor_again2 = torch.rand(size=(1,7))


# Matrix multiply tensors
multi = rand_tensor_again @ rand_tensor_again2.T

print(multi,',', multi.shape)



tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) , torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU

torch.cuda.seed(1234)


TypeError: seed() takes 0 positional arguments but 1 was given


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [23]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
if torch.cuda.is_available():
    print('Device: cuda')
    torch.cuda.seed()
else:
    print("GPU is not available")


# Create two random tensors on GPU
# rand_tensor = torch.rand(size=(2,3), device='cuda')
# rand_tensor2 = torch.rand(size=(2,3), device='cuda')


# Using cpu
rand_tensor = torch.rand(size=(2,3), device='cpu')
rand_tensor2 = torch.rand(size=(2,3), device='cpu')

print(rand_tensor, rand_tensor.device)
print(rand_tensor2, rand_tensor.device)


GPU is not available
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cpu
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]) cpu



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [29]:
# Perform matmul on tensor_A and tensor_B

prod = rand_tensor @ rand_tensor2.T

print(prod, prod.device, prod.size())


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) cpu torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [30]:
# Find max
print(prod.min())

# Find min
print(prod.max())


tensor(0.3647)
tensor(0.5617)


### 9. Find the maximum and minimum index values of the output of 7.

In [31]:
# Find arg max
print(prod.argmax())

# Find arg min
print(prod.argmin())


tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [33]:
# Set seed
torch.manual_seed(7)


# Create random tensor
tensor1 = torch.rand(size=(1,1,1,10))


# Remove single dimensions
tensor2 = torch.squeeze(tensor1)


# Print out tensors and their shapes
print(tensor1, tensor1.shape)
print(tensor2, tensor2.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
